---
- hosts: spectator
  remote_user: pi
  become: true
#  vars_files:
#    - vars_spectator-local.yml
# NOTE: SPECIFY VARS ON COMMAND LINE CALL

  tasks:
    - name: Network | Set up networking-related files.
      template:
        src: "templates/spectator/{{ item.template }}"
        dest: "{{ item.dest }}"
        mode: 0644
      with_items:
        - { template: hostname.j2, dest: /etc/hostname }
        - { template: hosts.j2, dest: /etc/hosts }
        - { template: 10-eth0.netdev.j2, dest: /etc/systemd/network/10-eth0.netdev }
        - { template: 10-wlan0.network.j2, dest: /etc/systemd/network/10-wlan0.network }
        - { template: 11-eth0.network.j2, dest: /etc/systemd/network/11-eth0.network }
        - { template: wpa_supplicant-wlan0.conf.j2, dest: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf }
        - { template: dnsmasq.conf.j2, dest: /etc/dnsmasq.conf }
        - { template: chrony.conf.j2, dest: /etc/chrony/chrony.conf }
      notify:
        - Network | update hostname
        - Network | Delete dhcp leases

########################### SYSTEM SETUP ###########################

    - name: System setup | Update all installed apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: true
      no_log: true

    - name: System setup | Install basic packages
      apt:
        pkg:
          - nfs-kernel-server
          - vim
          - rsync
          - dnsmasq
          - tcpdump
          - chrony
          - git
          - htop
          - byobu
          - python3-pip
          - python3-zmq
          - python3-apt
          - python-setuptools  # workaround for ansible checking setuptools of the wrong python version!
        state: present

    - name: System setup | Install pip packages
      pip:
        name:
          - pyyaml
        executable: pip3

########################### NETWORK ############################

    - name: Network | enable dnsmasq service
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

    - name: Network | enable networkd service
      systemd:
        name: systemd-networkd
        enabled: yes
        state: restarted

    - name: Network | disable dhcpcd service
      systemd:
        name: systemd-networkd
        enabled: no
        state: stopped

########################### HANDLERS ###########################

  handlers:
    - name: Network | update hostname
      hostname:
        name: spectator

    - name: Network | Delete dhcp leases
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/misc/dnsmasq.leases
        - /var/lib/dhcp/dhclient.leases
        - /var/lib/dhcpcd5/dhcpcd-eth0.lease

